# Generated by Django 3.0.3 on 2020-03-04 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('releaseDate', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField()),
                ('complete', models.BooleanField()),
                ('senderId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentId', models.CharField(max_length=200)),
                ('departmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directionId', models.CharField(max_length=200, unique=True)),
                ('directionName', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notId', models.IntegerField()),
                ('message', models.CharField(max_length=1000)),
                ('activityId', models.IntegerField()),
                ('notDate', models.DateField(default=datetime.date.today)),
                ('receiverId', models.CharField(max_length=200)),
                ('isShown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeptDirector',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Employee')),
                ('department', models.CharField(max_length=200)),
            ],
            bases=('activities.employee',),
        ),
        migrations.CreateModel(
            name='OfficeClerk',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Employee')),
                ('department', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=200)),
            ],
            bases=('activities.employee',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('numberOfTasks', models.IntegerField()),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('receiverId', models.CharField(max_length=100)),
                ('projectId', models.IntegerField()),
                ('approved', models.BooleanField()),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeId', models.CharField(max_length=200)),
                ('officeName', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Direction'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.IntegerField()),
                ('message', models.CharField(max_length=2000)),
                ('sentBySender', models.BooleanField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Task')),
            ],
        ),
    ]
